webserver/config/routes.rb
Rails.application.routes.draw do
  resources :songs

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'songs#index'
  get 'new' => 'songs#new'
  get 'block' => 'songs#block'

  post 'analyze' => 'apis#analyze'
  post 'attach' => 'apis#attach'
  post 'detach' => 'apis#detach'

  get 'detector' => 'apis#index'
  get 'status' => 'apis#status'
  post 'feel' => 'apis#feel'

  get 'contain' => 'apis#contain'

  get 'api/SongManager/Get/:id' => 'apis#song_info'

  root 'songs#index'

end

webserver/app/models/song.rb
class Song < ActiveRecord::Base
  validates :title, presence: true
  validates :fingerprint, presence: true
  validates :fingerprint_hash, presence: true
  validates_uniqueness_of :fingerprint_hash, message: "This song has already been added"
  validates :url, format: { with: /\A((http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?)?\z/ix }
end

webserver/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    if (!logged_in?);
      redirect_to login_path
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    if (!logged_in?);
      redirect_to login_path
    end
  end

  # GET /songs/new
  def new
    if (!logged_in?);
      redirect_to login_path
    end
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
    if !logged_in?;
      redirect_to login_path
    end
  end

  # POST /songs
  # POST /songs.json
  def create
    if !logged_in?;
      redirect_to login_path
    end

    prs = song_params.permit(:url, :title, :author, :artist, :image, :mini_image, :fingerprint, :fingerprint_hash, :lyrics)

    @song = Song.new(prs)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song; flash[:success] = 'Song was successfully created.' }
        # format.json { render :show, status: :created, location: @song }
      else
        @errors = @song
        format.html { render :new }
        # format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    if !logged_in?;
      redirect_to login_path
    end

    prs = song_params.permit(:url, :title, :author, :artist, :image, :mini_image, :fingerprint, :fingerprint_hash, :lyrics)

    respond_to do |format|
      if @song.update(prs)
        Thread.new do
          result = JSON.parse (detach_song @song.id)
          if result["Verdict"] == "Yes"
            attach_song @song.id, @song.fingerprint
          end
        end
        format.html { sleep 0.5; redirect_to @song; flash[:success] = 'Song was successfully updated.' }
        # format  .json { render :show, status: :ok, location: @song }
      else
        @errors = @song
        format.html { render :edit }
        # format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    if !logged_in?;
      return
    end
    @song.destroy
    Thread.new do
      detach_song @song.id
    end

    respond_to do |format|
      format.html { redirect_to songs_url; flash[:success] = 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /block?query=...&offset=...
  def block
    if !logged_in?
      return
    end
    offset = params["offset"]
    limit = 6
    query = params["query"]
    result = Song.limit(limit).offset(offset)
                 .where("#{:title} LIKE ? OR #{:author} LIKE ? OR #{:artist} LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
                 .select(:id, :title, :author, :artist, :mini_image)
    if (result.empty?)
      render text: ""
    else
      next_offset = Song.pluck(:id).index(result.last.id) + 1
      render partial: 'songs/element_index', locals: { result: result, offset: next_offset}
    end

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_song
    @song = Song.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def song_params
    params[:song]
  end

end

webserver/app/helpers/songs_helper.rb
module SongsHelper

end

webserver/app/views/songs/_element_index.html.erb
<% result.each do |song| %>
    <div class="display-block-spacing grid-item col-xs-6 col-sm-4 col-md-3 col-lg-2"
         style="display: none"
         id="grid-item-<%= song.id %>">
      <div class="display-block img-rounded image">

        <img class="img-rounded" style="width: 100%; height: 100%" id="imgSong-<%= song.id %>"
             src="<%= song.mini_image == "" ? image_path("default-artist.jpg") : "data:image/jpg;base64," + song.mini_image %>"
             onclick="location.href='<%= song_path(song)%>';">

        <h3>
          <span id="title-<%= song.id %>"><%= song.title %></span>
        </h3>
        <span style="font-size: 16px; display: block"><%= song.artist == "" ? "Artist not available" : song.artist %></span>
        <a onclick="adSong(<%= song.id %>)" disabled status="0" id="adSong-<%= song.id %>" style="color: white; width: 65%"
           class="btn btn-info" song-id="<%= song.id %>">
          <i class="glyphicon glyphicon-off"></i> ...
        </a>

        <%= link_to "", song, id: ("rmSong-" + song.id.to_s), style: "display: none" %>
        <a onclick="rmSong(<%= song.id %>)" id="rmSong-btn-<%= song.id %>" style="float:right; width: 30%" class="btn btn-danger">
          <i class="glyphicon glyphicon-trash"></i>
        </a>

      </div>
    </div>
<% end %>
<div next-offset="<%= offset %>"></div>

webserver/app/views/songs/edit.html.erb
<%= form_for @song do |f| %>
    <div class="container">
      <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2">

          <h1>Edit song "<b style="color: green"><%= @song.title %></b>"</h1>
          &nbsp
          <table class="table">
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :url, "Url", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <div class="input-group" style="width:100%;">
                  <span class="input-group-addon">
                    <i class="glyphicon glyphicon-link"></i>
                  </span>
                  <%= f.text_field :url, class: "form-control", placeholder: "Url of the song" %>
                  <span class="input-group-btn">
                    <input disabled type="button" value="Analyze Url (Disabled function)" id="analyze_url" class="btn btn-feedback"/>
                  </span>

                </div>

              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :title, "Title", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <div class="input-group" style="width: 100%">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-music"></i></span>
                  <%= f.text_field :title, class: "form-control", placeholder: "Title of the song (cannot be blank)" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td rowspan="3" class="col-xs-1">
                <label class="control-label" for="artist_image">Image</label>
              </td>
              <td rowspan="3" class="col-xs-5">
                <div class="input-group">
                  <%= f.hidden_field :image, id: "image" %>
                  <%= f.hidden_field :mini_image, id: "mini_image" %>
                  <label for="choose_image">
                    <%= image_tag (@song.image == "" ? "default-artist.jpg" : "data:image/jpg;base64," + @song.image),
                                  id: "artist_image", alt: "Ảnh đại diện",
                                  class: "col-ld-5 thumb img-thumbnail",
                                  style: "height:250px;width:250px;",
                                  title: "Click on Image to choose another" %>
                  </label>
                  <input class="hidden" type="file" accept="image/jpeg,image/png,image/gif" id="choose_image" name="Choose_Image"/>
                </div>
              </td>

              <td class="col-xs-1">
                <%= f.label :author, "Author", class: "control-label" %>
              </td>
              <td class="col-xs-5">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                  <%= f.text_field :author, class: "form-control", placeholder: "Author of the song" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :artist, "Artist", class: "control-label" %>
              </td>
              <td class="col-xs-5">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                  <%= f.text_field :artist, class: "form-control", placeholder: "Artist of the song" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <label for="finger_print_status">Fingerprint</label>
              </td>
              <td class="col-xs-5">
                <span style="font-weight:bold;">Ready? <span style="color:green;" id="finger_print_status">Yes</span></span>

                <div>
                  <input id="file_path" class="form-control" readonly="" type="text"
                         value="<%= "{Length:#{@song.fingerprint.length},Data='#{@song.fingerprint[0..49]}...'}" %>">
                </div>

                &nbsp
                <div>
                  <span class="btn btn-primary btn-file" style="float:left; width: 125px">
                    Choose a song<input id="choose_song" class="form-control" type="file" accept="audio/wav, audio/mp3">
                  </span>
                  <span style="float: left;">&nbsp</span>
                  <input type="button" style="float: left; width: 125px" id="analyze" value="Analyze song" class="btn btn-primary"/>
                </div>
                <%= f.hidden_field :fingerprint, id: "fingerprint" %>
                <%= f.hidden_field :fingerprint_hash, id: "fingerprint_hash" %>
                <span class="hidden" id="file_data"></span>
                <span class="hidden" id="file_type"></span>

              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :lyrics, "Lyrics", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <%= f.text_area :lyrics, style: "resize:vertical;", class: "form-control", placeoholder: "Lyrics of the song", rows: "10" %>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1"></td>
              <td class="col-xs-11" colspan="3">
                <button style="color: white; width: 100px" type="submit" class="btn btn-success" id="submit">
                  <i class="glyphicon glyphicon-floppy-disk"></i> Save
                </button>
                <a style="color: white; width: 100px" class="btn btn-danger" href="<%= song_path(@song) %>">
                  <i class="glyphicon glyphicon-trash"></i> Cancel</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
<% end %>
<script>
    $(document).ready(function () {
        if ($('#fingerprint').val() == "") {
            validateError("#file_path");
            $('#file_path').css("color", "red");
            $('#file_path').val("");
            $('#finger_print_status').removeAttr("style").css("color", "red").html("No");
        } else {
            validateSuccess("#file_path");
            $('#file_path').css("color", "green");
        }
    });
    <%= render 'scripts/new_edit.js' %>
</script>

webserver/app/views/songs/index.html.erb
<div class="container col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3">
  <form role="form" action="<%= home_path %>" method="GET">
    <div class="form-group">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="What are you looking for?" name="query"
               value="<%= params[:query] ? params[:query] : "" %>">
        <span class=" input-group-btn"> <input class="btn btn-success" type="submit" value="Search"> </span>
      </div>
    </div>
  </form>
  <h3 align="center" id="no-record" style="display: none; color: red"><br>No records found.</h3>
</div>

<div class="container col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xs-offset-0 col-sm-offset-0 col-md-offset-0 col-lg-offset-0">

  <div class="lazy-load">
  </div>

  <div class="col-xs-2 col-xs-offset-5">
    <div id="marker"></div>
    <div>&nbsp</div>
    <%= image_tag "loading.gif", id: "loader", style: "width: 100%; height: 100%" %>
    <div>&nbsp</div>
  </div>


</div>
<input id="query" type="hidden" value="<%= params[:query] ? params[:query] : "" %>">
<script>
    <%= render 'scripts/index.js' %>
</script>

webserver/app/views/songs/new.html.erb
<%= form_for @song do |f| %>
    <div class="container">
      <div class="row clearfix">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2">

          <h1>Add a new song</h1>
          &nbsp
          <table class="table">
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :url, "Url", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <div class="input-group" style="width:100%;">
                  <span class="input-group-addon">
                    <i class="glyphicon glyphicon-link"></i>
                  </span>
                  <%= f.text_field :url, class: "form-control", placeholder: "Url of the song" %>
                  <span class="input-group-btn">
                    <input disabled type="button" value="Analyze Url (Disabled function)" id="analyze_url" class="btn btn-feedback"/>
                  </span>

                </div>

              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :title, "Title", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <div class="input-group" style="width: 100%">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-music"></i></span>
                  <%= f.text_field :title, class: "form-control", placeholder: "Title of the song (cannot be blank)" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td rowspan="3" class="col-xs-1">
                <label class="control-label" for="artist_image">Image</label>
              </td>
              <td rowspan="3" class="col-xs-5">
                <div class="input-group">
                  <%= f.hidden_field :image, id: "image" %>
                  <%= f.hidden_field :mini_image, id: "mini_image" %>
                  <label for="choose_image">
                    <%= image_tag "default-artist.jpg",
                                  id: "artist_image", alt: "Ảnh đại diện",
                                  class: "col-ld-5 thumb img-thumbnail",
                                  style: "height:250px;width:250px;",
                                  title: "Click on Image to choose another" %>
                  </label>
                  <input class="hidden" type="file" accept="image/jpeg,image/png,image/gif" id="choose_image" name="Choose_Image"/>
                </div>
              </td>

              <td class="col-xs-1">
                <%= f.label :author, "Author", class: "control-label" %>
              </td>
              <td class="col-xs-5">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
                  <%= f.text_field :author, class: "form-control", placeholder: "Author of the song" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :artist, "Artist", class: "control-label" %>
              </td>
              <td class="col-xs-5">
                <div class="input-group">
                  <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                  <%= f.text_field :artist, class: "form-control", placeholder: "Artist of the song" %>
                </div>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <label for="finger_print_status">Fingerprint</label>
              </td>
              <td class="col-xs-5">
                <span style="font-weight:bold;">Ready? <span style="color:red;" id="finger_print_status">No</span></span>

                <div>
                  <input id="file_path" class="form-control" readonly="" type="text">
                </div>

                &nbsp
                <div>
                  <span class="btn btn-primary btn-file" style="float:left; width: 125px">
                    Choose a song<input id="choose_song" class="form-control" type="file" accept="audio/wav, audio/mp3">
                  </span>
                  <span style="float: left;">&nbsp</span>
                  <input type="button" style="float: left; width: 125px" id="analyze" value="Analyze song" class="btn btn-primary"/>
                </div>
                <%= f.hidden_field :fingerprint, id: "fingerprint", value: "" %>
                <%= f.hidden_field :fingerprint_hash, id: "fingerprint_hash", value: "0" %>
                <span class="hidden" id="file_data"></span>
                <span class="hidden" id="file_type"></span>

              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1">
                <%= f.label :lyrics, "Lyrics", class: "control-label" %>
              </td>
              <td colspan="3" class="col-xs-11">
                <%= f.text_area :lyrics, style: "resize:vertical;", class: "form-control", placeoholder: "Lyrics of the song", rows: "10" %>
              </td>
            </tr>
            <tr class="row">
              <td class="col-xs-1"></td>
              <td class="col-xs-11" colspan="3">
                <button style="color: white; width: 100px" type="submit" class="btn btn-success" id="submit">
                  <i class="glyphicon glyphicon-plus"></i> Add
                </button>
                <a style="color: white; width: 100px" class="btn btn-danger" href="<%= home_path %>">
                  <i class="glyphicon glyphicon-trash"></i> Cancel</a>
              </td>
            </tr>
          </table>
        </div>
      </div>
    </div>
<% end %>

<script>
    <%= render 'scripts/new_edit.js' %>
</script>

webserver/app/views/songs/show.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-xs-12 col-sm-12 col-md-10 col-lg-8 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-2">
      <h1>Song information</h1>
      &nbsp
      <table class="table">
        <tr class="row">
          <td class="col-xs-1">
            <label class="control-label">Url</label>
          </td>
          <td colspan="3" class="col-xs-11">
            <div class="input-group" style="width:100%;">
                  <span class="input-group-addon">
                    <i class="glyphicon glyphicon-link"></i>
                  </span>
              <input readonly type="text" placeholder="Empty url" class="form-control" value="<%= @song.url %>"/>
            </div>

          </td>
        </tr>
        <tr class="row">
          <td class="col-xs-1">
            <label class="control-label">Title</label>
          </td>
          <td colspan="3" class="col-xs-11">
            <div class="input-group" style="width: 100%">
              <span class="input-group-addon"><i class="glyphicon glyphicon-music"></i></span>
              <input readonly type="text" placeholder="Empty title" class="form-control" value="<%= @song.title %>"/>
            </div>
          </td>
        </tr>
        <tr class="row">
          <td rowspan="3" class="col-xs-1">
            <label class="control-label">Image</label>
          </td>
          <td rowspan="3" class="col-xs-5">
            <div class="input-group">
              <%= image_tag (@song.image == "" ? "default-artist.jpg" : "data:image/jpg;base64," + @song.image),
                            id: "artist_image", alt: "Ảnh đại diện",
                            class: "thumb img-thumbnail",
                            style: "width:250px;height:250px;",
                            title: "Click on Image to choose another" %>
            </div>
          </td>

          <td class="col-xs-1">
            <label class="control-label">Author</label>
          </td>
          <td class="col-xs-5">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
              <input readonly type="text" placeholder="Empty author" class="form-control" value="<%= @song.author %>"/>
            </div>
          </td>
        </tr>
        <tr class="row">
          <td class="col-xs-1">
            <label class="control-label">Artist</label>
          </td>
          <td class="col-xs-5">
            <div class="input-group">
              <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
              <input readonly type="text" placeholder="Empty artist" class="form-control" value="<%= @song.artist %>"/>
            </div>
          </td>
        </tr>
        <tr class="row">
          <td class="col-xs-1">
            <label for="finger_print_status">Fingerprint</label>
          </td>
          <td class="col-xs-5">
            <span style="font-weight:bold;">Ready? <span style="color:green;">Yes</span></span>

            <div>

              <input class="form-control" readonly type="text" value="<%= "{Length:#{@song.fingerprint.length},Data:'#{@song.fingerprint[0..49]}...'}" %>">
            </div>

            &nbsp
            <div style="width: 300px">
            </div>
          </td>
        </tr>
        <tr class="row">
          <td class="col-xs-1">
            <label class="control-label">Lyrics</label>
          </td>
          <td colspan="3" class="col-xs-11">
            <textarea readonly style="resize:vertical;" class="form-control" placeholder="Empty lyrics" rows="10"><%= @song.lyrics %></textarea>
          </td>
        </tr>
        <tr class="row">
          <td class="col-xs-1"></td>
          <td class="col-xs-11" colspan="3">
            <a disabled status="0" id="adSong" style="color: white; width: 100px" class="btn btn-info" song-id="<%= @song.id %>">
              <i class="glyphicon glyphicon-off"></i> ...
            </a>
            <a style="color: white; width: 100px" class="btn btn-danger" href="<%= edit_song_path @song %>">
              <i class="glyphicon glyphicon-edit"></i> Edit
            </a>
            <a style="color: white; width: 100px" class="btn btn-primary" href="<%= home_path %>">
              <i class="glyphicon glyphicon-home"></i> Home
            </a>

            <%= link_to "", @song, {method: :delete, id: "rmSong", style: "display: none"} %>
            <a id="rmButton" style="float:right; color: white" class="btn btn-danger">
              <i class="glyphicon glyphicon-trash"></i> Remove
            </a>


          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
<script>
    <%= render 'scripts/show.js' %>
</script>