webserver/config/routes.rb
Rails.application.routes.draw do
  resources :songs

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'songs#index'
  get 'new' => 'songs#new'
  get 'block' => 'songs#block'

  post 'analyze' => 'apis#analyze'
  post 'attach' => 'apis#attach'
  post 'detach' => 'apis#detach'

  get 'detector' => 'apis#index'
  get 'status' => 'apis#status'
  post 'feel' => 'apis#feel'

  get 'contain' => 'apis#contain'

  get 'api/SongManager/Get/:id' => 'apis#song_info'

  root 'songs#index'

end

webserver/app/views/scripts/_index.js.erb
var updateActionButton = function (id) {
    var button = "#adSong-" + id;
    $.ajax({
        type: "GET",
        url: "<%= contain_path %>",
        data: {Key: $(button).attr("song-id")},
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            if (data.Verdict == "Yes") {
                $(button).removeAttr('disabled');
                if (data.Result == "No") {
                    $(button).removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-success");
                    $(button).attr("status", "-1")
                    $(button).html('<i class="glyphicon glyphicon-save"></i> Attach');
                } else {
                    $(button).removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-warning");
                    $(button).attr("status", "1")
                    $(button).html('<i class="glyphicon glyphicon-open"></i> Detach');
                }
            }
        },
        error: function () {
            $(button).attr('disabled', 'disabled');
            $(button).removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-info");
            $(button).attr("status", "0");
            $(button).html('<i class="glyphicon glyphicon-off"></i> ...');
        }
    });
}

var adSong = function (id) {
    var button = "#adSong-" + id;
    var jsonObj = {};
    jsonObj["Key"] = $(button).attr('song-id');

    var oldStatus = $(button).attr("status");
    if (oldStatus == "-1") {
        $.ajax({
            type: "POST",
            url: "<%= attach_path %>",
            data: JSON.stringify(jsonObj),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $(button).attr('disabled', 'disabled');
            },
            complete: function () {
                updateActionButton(id);
            }
        });

    } else if (oldStatus == "1") {
        $.ajax({
            type: "POST",
            url: "<%= detach_path %>",
            data: JSON.stringify(jsonObj),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $(button).attr('disabled', 'disabled');
            },
            complete: function () {
                updateActionButton(id);
            }
        });
    }
}

var grid = $('.lazy-load').masonry({
    itemSelector: '.grid-item'
});

var next_offset = 0;
var count_record = 0;
$(document).ready(function () {
    $('#marker').on('lazyshow', function () {
        $.ajax({
            type: "GET",
            url: "<%= block_path %>",
            data: {query: $("#query").val(), offset: next_offset},
            contentType: 'application/json; charset=utf-8',
            success: function (responseText) {

                $('.lazy-load').append(responseText);

                grid.masonry('reloadItems');
                grid.masonry('layout');

                if (responseText == "") {
                    $('#loader').hide();
                    if (count_record == 0) {
                        $('#no-record').show();
                    }

                    return;
                }

                var ids = responseText.match(/grid-item-\d+/g);
                count_record += ids.length;
                for (var i = 0; i < ids.length; ++i) {
                    $('#' + ids[i]).show();
                    updateActionButton(ids[i].substr(10));
                }

                var tmp = responseText.indexOf('next-offset="') + 13;
                next_offset = parseInt(responseText.substring(tmp, responseText.indexOf('"', tmp)));
                $('#marker').lazyLoadXT({visibleOnly: false, checkDuplicates: false});
            },
            error: function () {
                $('#marker').lazyLoadXT({visibleOnly: false, checkDuplicates: false});
            }
        });
    }).lazyLoadXT({visibleOnly: false});
});

var rmSong = function (id) {
    var title = $('#title-' + id).html();
    bootbox.confirm("Are you sure to remove song '" + title + "'?", function (result) {
        if (result) {
            $.ajax({
                type: "DELETE",
                url: $('#rmSong-' + id).attr("href") + ".json",
                dataType: 'json',
                beforeSend: function() {
                    $('#rmSong-btn-' + id).attr("disabled", "disabled");
                    $('#adSong-' + id).attr("disabled", "disabled");
                    $('#imgSong-' + id).removeAttr("onclick");
                },
                success: function() {
                    $('#grid-item-' + id).remove();
                    grid.masonry('reloadItems');
                    grid.masonry('layout');
                },
                error: function() {
                    bootbox.dialog({
                        message: "Server internal error...",
                        title: "Alert",
                        buttons: {
                            danger: {
                                label: "Return",
                                className: "btn-danger",
                            }
                        }
                    });
                }
            });
        }
    });
}

webserver/app/views/scripts/_new_edit.js.erb
/**
 * Created by hovinhthinh on 1/23/16.
 */

var validateNormal = function (target) {
    target = $(target);
    while (target.get(0).tagName != 'DIV') {
        target = target.parent()
    }
    target.removeClass("has-error").removeClass("has-feedback").removeClass("has-warning").removeClass("has-success");
};

var validateSuccess = function (target) {
    target = $(target);
    while (target.get(0).tagName != 'DIV') {
        target = target.parent()
    }
    target.removeClass("has-error").removeClass("has-feedback").removeClass("has-warning").addClass("has-success");
};

var validateError = function (target) {
    target = $(target);
    while (target.get(0).tagName != 'DIV') {
        target = target.parent()
    }
    target.removeClass("has-success").removeClass("has-feedback").removeClass("has-warning").addClass("has-error");
};

$('#choose_image').change(function () {
    var files = this.files;
    var file = this.files[0];
    if (file != null) {
        var reader = new FileReader();
        reader.onloadend = function (e) {
            var res = e.target.result;
            $('#artist_image').attr('src', res);
            //resize
            var tempImg = new Image();
            tempImg.src = reader.result;
            tempImg.onload = function () {
                var MAX_WIDTH = 200;
                var MAX_HEIGHT = 200;

                var canvas = document.createElement('canvas');
                canvas.width = MAX_WIDTH;
                canvas.height = MAX_HEIGHT;
                var ctx = canvas.getContext("2d");
                ctx.drawImage(this, 0, 0, MAX_WIDTH, MAX_HEIGHT);
                var dataURL = canvas.toDataURL("image/jpeg");
                var data = dataURL.split(',')[1];
                $('#mini_image').attr('value', data);

                MAX_WIDTH = 400;
                MAX_HEIGHT = 400;
                canvas = document.createElement('canvas');
                canvas.width = MAX_WIDTH;
                canvas.height = MAX_HEIGHT;
                ctx = canvas.getContext("2d");
                ctx.drawImage(this, 0, 0, MAX_WIDTH, MAX_HEIGHT);
                dataURL = canvas.toDataURL("image/jpeg");

                data = dataURL.split(',')[1];
                $('#image').attr('value', data);
            }
        }
        reader.readAsDataURL(file);

    }
});

$('#choose_song').change(function () {

    var files = this.files;
    var file = this.files[0];
    if (file != null) {
        var reader = new FileReader();
        reader.onloadend = function (e) {
            var res = e.target.result;
            var base64 = res.split(',')[1];
            $('#file_data').empty();
            $('#file_data').html(base64);
            $('#file_path').removeAttr('style').val(file.name);
            validateNormal('#file_path');
            var arr = file.name.split('.');
            $('#file_type').html(arr[arr.length - 1].toLowerCase());
            $('#finger_print_status').html("No").removeAttr('style').css("color", "red")
            $('#fingerprint').val("");

            if (base64 == null || base64 == "") {
                $('#file_path').removeAttr('style').css('color', 'red');
                $('#file_path').val('Empty file. Please choose another...');
                validateError("#file_path");
            }
        };
        reader.readAsDataURL(file);
        $('#choose_song').val("");
    } else {
    }
});
// Analyze by uploading
$('#analyze').on('click', function () {
    // validate if a song is pick up
    var str = $('#file_data').html();
    if (str == null || str == "") {
        $('#file_path').removeAttr('style').css('color', 'red');
        $('#file_path').val('Please choose a song...');
        validateError("#file_path");
        return;
    }
    // Prepare data for uploading
    jsonObj = {};
    jsonObj["Content"] = str;
    jsonObj["Type"] = $('#file_type').html();

    $.ajax({
        type: "POST",
        url: "<%= analyze_path %>",
        data: JSON.stringify(jsonObj),
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        beforeSend: function () {
            // Disable elements
            $('#analyze').prop('disabled', true);
            $('#submit').prop('disabled', true);
            $('#analyze').attr('value', 'Analyzing...')
        },
        success: function (data) {
            if (data.Verdict == "Yes") {
                $('#fingerprint').val(data.Fingerprint);
                $('#fingerprint_hash').val(data.FingerprintHash);
                validateSuccess('#file_path');
                $('#file_path').removeAttr('style').css('color', 'green');
                $('#finger_print_status').html("Yes").removeAttr('style').css("color", "green")
            } else {
                validateError('#file_path');
                $('#finger_print_status').html("No").removeAttr('style').css("color", "red")
                $('#file_data').empty();
                $('#file_path').removeAttr('style').css('color', 'red');
                $('#file_path').val("Error with song file...")
                $('#fingerprint').val("");
            }
        },
        error: function () {
            validateError('#file_path');
            $('#finger_print_status').html("No").removeAttr('style').css("color", "red")
            $('#file_data').html("");
            $('#file_path').removeAttr('style').css('color', 'red');
            $('#file_path').val("Server internal error...")
            $('#fingerprint').val("");
        },
        complete: function () {
            $('#analyze').prop('disabled', false);
            $('#submit').prop('disabled', false);
            $('#analyze').attr('value', 'Analyze song')
        }
    });
});

webserver/app/views/scripts/_show.js.erb
/**
 * Created by hovinhthinh on 1/25/16.
 */
$(".form-control").each(function () {
    if ($(this).val() != "") {
        $(this).css("color", "green");
    }
});

$('#rmButton').on('click', function () {
    bootbox.confirm("Are you sure to remove song '<%= @song.title %>'?", function (result) {
        if (result) {
            $('#rmSong').trigger('click');
        }
    });
});

var updateActionButton = function () {
    $.ajax({
        type: "GET",
        url: "<%= contain_path %>",
        data: {Key: $('#adSong').attr("song-id")},
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        success: function (data) {
            if (data.Verdict == "Yes") {
                $('#adSong').removeAttr('disabled');
                if (data.Result == "No") {
                    $('#adSong').removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-success");
                    $('#adSong').attr("status", "-1")
                    $('#adSong').html('<i class="glyphicon glyphicon-save"></i> Attach');
                } else {
                    $('#adSong').removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-warning");
                    $('#adSong').attr("status", "1")
                    $('#adSong').html('<i class="glyphicon glyphicon-open"></i> Detach');
                }
            }
        },
        error: function () {
            $('#adSong').attr('disabled', 'disabled');
            $('#adSong').removeClass("btn-info").removeClass("btn-success").removeClass("btn-warning").addClass("btn-info");
            $('#adSong').attr("status", "0");
            $('#adSong').html('<i class="glyphicon glyphicon-off"></i> ...');
        }
    });
}
$(document).ready(function () {
    updateActionButton();
});


$('#adSong').on('click', function () {
    var jsonObj = {};
    jsonObj["Key"] = $(this).attr('song-id');

    var oldStatus = $(this).attr("status");
    if (oldStatus == "-1") {
        $.ajax({
            type: "POST",
            url: "<%= attach_path %>",
            data: JSON.stringify(jsonObj),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $('#adSong').attr('disabled', 'disabled');
            },
            complete: function () {
                updateActionButton();
            }
        });

    } else if (oldStatus == "1") {
        $.ajax({
            type: "POST",
            url: "<%= detach_path %>",
            data: JSON.stringify(jsonObj),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            beforeSend: function () {
                $('#adSong').attr('disabled', 'disabled');
            },
            complete: function () {
                updateActionButton();
            }
        });
    }
});