webserver/config/routes.rb
Rails.application.routes.draw do
  resources :songs

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'songs#index'
  get 'new' => 'songs#new'
  get 'block' => 'songs#block'

  post 'analyze' => 'apis#analyze'
  post 'attach' => 'apis#attach'
  post 'detach' => 'apis#detach'

  get 'detector' => 'apis#index'
  get 'status' => 'apis#status'
  post 'feel' => 'apis#feel'

  get 'contain' => 'apis#contain'

  get 'api/SongManager/Get/:id' => 'apis#song_info'

  root 'songs#index'

end

webserver/app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<div class="footer-distributed">

  <div class="footer-right">

    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>

  </div>

  <div class="footer-left">

    <p class="footer-links">
        SongFeeler Web Gate
    </p>

    <p> &copy; 2015 - By Hồ Vĩnh Thịnh</p>
  </div>

</div>

webserver/app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">
        <span style="color: darkviolet; font-size: larger; font-family: Monaco">SongFeeler Web Gate</span>
      </a>
    </div>
    <% if logged_in? %>
        <div class="collapse navbar-collapse" id="navbar-ex-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li>
              <a rel="nofollow" data-method="delete" href="<%= logout_path %>">
                Logout <i class="glyphicon glyphicon-log-out"></i>
              </a>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-left">
            <li class="active">
              <a rel="nofollow" href="<%= home_path %>">
                <i class="glyphicon glyphicon-home"></i> Home
              </a>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                 aria-expanded="false">Action <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <a rel="nofollow" href="<%= home_path %>">
                    <i class="glyphicon glyphicon glyphicon-list-alt"></i> View all songs
                  </a>
                </li>
                <li>
                  <a rel="nofollow" href="<%= new_path %>">
                    <i class="glyphicon glyphicon glyphicon-plus"></i> Add a new song
                  </a>
                </li>
                <li class="divider"></li>
                <li>
                  <%= link_to detector_path do %>
                      <i class="glyphicon glyphicon-flash"></i> Detector status
                  <% end %>
                </li>
              </ul>
            </li>
          </ul>

        </div>

    <% end %>
  </div>
</div>

webserver/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Songfeeler Web Gate</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <div>
    &nbsp
  </div>
  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= render 'shared/error_messages' %>

  <%= yield %>
</div>
<%= render 'layouts/footer' %>
<%= "" #debug(params) if Rails.env.development?
%>

</body>
</html>