webserver/config/routes.rb
Rails.application.routes.draw do
  resources :songs

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'home' => 'songs#index'
  get 'new' => 'songs#new'
  get 'block' => 'songs#block'

  post 'analyze' => 'apis#analyze'
  post 'attach' => 'apis#attach'
  post 'detach' => 'apis#detach'

  get 'detector' => 'apis#index'
  get 'status' => 'apis#status'
  post 'feel' => 'apis#feel'

  get 'contain' => 'apis#contain'

  get 'api/SongManager/Get/:id' => 'apis#song_info'

  root 'songs#index'

end

webserver/app/controllers/apis_controller.rb
require "uri"
require "net/http"

class ApisController < ApplicationController


  def index
    if !logged_in?;
      redirect_to login_path
    end
    @status = putting_status
    if @status[:message] != ""
      flash.now[:danger] = @status[:message];
    end
  end

  def feel
    if !logged_in?;
      redirect_to login_path
    end
    put_all
    head :no_content
  end

  def status
    if !logged_in?;
      redirect_to login_path
    end
    render json: putting_status
  end

  def analyze
    if !logged_in?;
      redirect_to login_path
    end
    http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
    http.use_ssl = false
    request = Net::HTTP::Post.new("/analyzeByUploading/", {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                                           'Accept' => 'application/json, text/javascript, */*; q=0.01'})
    request.body = params.permit("Type", "Content").to_json
    response = http.request(request)

    render json: response.body
  end

  def contain
    if !logged_in?;
      redirect_to login_path
    end

    http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
    http.use_ssl = false
    request = Net::HTTP::Get.new("/contain/?key=" + params["Key"], {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                                                    'Accept' => 'application/json, text/javascript, */*; q=0.01'})
    response = http.request(request)

    render json: response.body
  end

  def attach
    if !logged_in?;
      redirect_to login_path
    end
    song = Song.find(params["Key"])
    # use helper function
    render json: attach_song(song.id, song.fingerprint)
  end

  def detach
    if !logged_in?;
      redirect_to login_path
    end
    # use helper function
    render json: detach_song(params["Key"])
  end

  def song_info
    song = Song.find(params[:id])
    response = {
        "Title" => song.title,
        "Url" => song.url,
        "Author" => song.author,
        "Artist" => song.artist,
        "Lyrics" => song.lyrics,
        "Image" => song.image
    }.to_json

    render json: response
  end
end

webserver/app/helpers/apis_helper.rb
require 'set'

module ApisHelper
  def attach_song(id, fingerprint)
    http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
    http.use_ssl = false
    request = Net::HTTP::Post.new("/add/", {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                            'Accept' => 'application/json, text/javascript, */*; q=0.01'})
    request.body = {"Key" => id, "Fingerprint" => fingerprint}.to_json
    http.request(request).body

  end

  def detach_song(id)
    http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
    http.use_ssl = false
    request = Net::HTTP::Get.new("/remove/?key=#{id}", {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                                             'Accept' => 'application/json, text/javascript, */*; q=0.01'})
    http.request(request).body
  end



  @@putting = nil
  @@mutex_queue = Mutex.new
  @@mutex_put = Mutex.new
  @@mutex_error = Mutex.new
  @@put = 0
  @@error = 0
  @@queue = []
  @@total = 0;
  def put_all
    if @@putting
      return
    end
    @@putting = 1
    begin
      http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
      http.use_ssl = false
      request = Net::HTTP::Get.new("/list/", {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                              'Accept' => 'application/json, text/javascript, */*; q=0.01'})
      attached = Set.new JSON.parse(http.request(request).body)["List"]
      @@put = attached.size
      @@error = 0
      @@queue = []
      current_attached = Song.pluck(:id)
      @@total = current_attached.length
      current_attached.each do |id|
        if !attached.include? id
          @@queue << id
        end
      end
      current_attached = nil

      threads = 4

      threads.times { @@queue << -1 }
      current = 0
      threads.times do
        Thread.new do
          begin
            id = -1
            @@mutex_queue.synchronize do
              id = @@queue[current]; current += 1
            end
            if id != -1
              begin
                song = Song.find id
                attach_song id, song.fingerprint
              rescue
                @@mutex_error.synchronize { @@error += 1}
              else
                @@mutex_put.synchronize { @@put += 1}
              end
            end
          end while id != -1
          if current == @@queue.length; @@putting = nil end
        end
      end

    rescue
      @@put = 0
      @@error = 0
      @@putting = nil
    end
  end

  def putting_status
    if (@@putting != nil)
      {
          status: "Yes",
          info: {
              total: @@total,
              put: @@put,
              error: @@error
          },
          message: ""
      }
    else
      total = 0
      message = ""
      begin
        http = Net::HTTP.new $DETECTOR_HOST, $DETECTOR_PORT
        http.use_ssl = false
        request = Net::HTTP::Get.new("/list/", {'Content-Type' => "application/x-www-form-urlencoded; charset=UTF-8;",
                                                            'Accept' => 'application/json, text/javascript, */*; q=0.01'})
        total = JSON.parse(http.request(request).body)["List"].length
      rescue
        message = "Cannot communicate with detector..."
      end
      {
          status: "No",
          info: {
              total: Song.count,
              put: total,
              error: @@error
          },
          message: message
      }
    end
  end
end

webserver/app/views/apis/index.html.erb
<div class="container col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1">
  <h1>Detector status</h1>
  &nbsp

  <table class="table">
    <tr class="row">
      <td class="col-xs-2" align="right"><b>Total songs:</b></td>
      <td class="col-xs-2" style="color: darkblue"><b id="num-total"></b></td>
      <td class="col-xs-2" align="right"><b>Attached songs:</b></td>
      <td class="col-xs-2" style="color: green"><b id="num-success"></b></td>
      <td class="col-xs-2" align="right"><b>Attaching errors:</b></td>
      <td class="col-xs-2" style="color: red"><b id="num-error"></b></td>
    </tr>
    <tr class="row">

    </tr>
    <tr class="row">
      <td class="col-xs-2" align="right"><b>Status:</b></td>
      <td class="col-xs-10" colspan="5">
        <div class="progress">
          <div id="pbs" class="progress-bar progress-bar-success"></div>
          <div id="pbe" class="progress-bar progress-bar-danger"></div>
        </div>
      </td>
    </tr>
    <tr class="row">
      <td colspan="6" class="col-xs-12" align="center">
        <a id="feel-btn" class="btn btn-primary" style="color: white; width: 225px">Attach all songs</a>
      </td>
    </tr>
  </table>
  <%
     stt = "ready"
     if @status[:message] != ""
       stt = "error"
     elsif @status[:status] == "Yes"
       stt = "putting"
     elsif @status[:info][:total] == @status[:info][:put]
       stt = "done"
     end
  %>
  <!-- error, putting, ready, done -->
  <input id="status" type="hidden" value="<%= stt %>"/>
</div>

<script>
    var activateBar = function () {
        $('#pbs').addClass("progress-bar-striped").addClass("active");
        $('#pbe').addClass("progress-bar-striped").addClass("active");
    }
    var deactivateBar = function () {
        $('#pbs').removeClass("progress-bar-striped").removeClass("active");
        $('#pbe').removeClass("progress-bar-striped").removeClass("active");
    }
    var setSuccess = function (c, t) {
        var p = t == 0 ? 0 : Math.floor(c * 100 / t);
        $('#pbs').html(p == 0 ? "" : p + "%");
        $('#pbs').removeAttr("style").css("width", (t == 0 ? 0 : c * 100 / t) + "%");
        $('#num-total').html(t);
        $('#num-success').html(c);
    }
    var setError = function (c, t) {
        var p = t == 0 ? 0 : Math.floor(c * 100 / t);
        $('#pbe').html(p == 0 ? "" : p + "%");
        $('#pbe').removeAttr("style").css("width", (t == 0 ? 0 : c * 100 / t) + "%");
        $('#num-total').html(t);
        $('#num-error').html(c);
    }
    var validateAttachButton = function () {
        if ($('#status').val() == "error") {
            $('#feel-btn').html("Server internal error...");
            $('#feel-btn').addClass("btn-danger");
            $('#feel-btn').attr("disabled", "disabled")
            return;
        }
        if ($('#num-total').html() == $('#num-success').html()) {
            $('#feel-btn').html("Everything is put!");
            $('#feel-btn').removeClass("btn-primary").addClass("btn-success");
            $('#feel-btn').attr("disabled", "disabled");
            deactivateBar();
        } else if ($('#status').val() == "putting") {
            $('#feel-btn').html("Songs are being attached...");
            $('#feel-btn').removeClass("btn-success").addClass("btn-primary");
            $('#feel-btn').attr("disabled", "disabled");
            activateBar();
        } else {
            $('#feel-btn').html("Attach all songs");
            $('#feel-btn').removeClass("btn-success").addClass("btn-primary");
            $('#feel-btn').removeAttr("disabled");
            deactivateBar();
        }

    }

    var listen = function () {
        setTimeout(function () {
            $.ajax({
                type: "GET",
                url: "<%= status_path %>",
                dataType: 'json',
                error: function () {
                    listen();
                },
                success: function (data) {
                    if (data.status == "Yes") {
                        setSuccess(data.info.put, data.info.total);
                        setError(data.info.error, data.info.total);
                        listen();
                    } else {
                        setSuccess(data.info.put, data.info.total);
                        setError(data.info.error, data.info.total);
                        $('#status').val("undefined");
                        validateAttachButton();
                    }
                }
            });
        }, 1000);
    }

    $('#feel-btn').on('click', function () {
        $.ajax({
            type: "POST",
            url: "<%= feel_path %>",
            beforeSend: function () {
                listen();
                $('#feel-btn').html("Songs are being attached...");
                $('#feel-btn').removeClass("btn-success").addClass("btn-primary");
                $('#feel-btn').attr("disabled", "disabled")
                activateBar();
            }
        });

    });
    $(document).ready(function () {
        setSuccess(<%= @status[:info][:put] %>, <%= @status[:info][:total] %>);
        setError(<%= @status[:info][:error] %>, <%= @status[:info][:total] %>);
        validateAttachButton();
        if ($('#status').val() == "putting") {
            listen();
        }
    });

</script>